[project]
name = "dishka-cyclopts"
version = "0.1.0"
description = "Dishka integration for cyclopts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
lint = ["pre-commit>=4.5.0", "ruff>=0.14.7"]
tests = ["pytest>=9.0.1"]
types = ["mypy>=1.19.0"]
